### ISSUE TITLE
Pet managed to get caught in an unloaded chunk, even if player has no pets.

### ISSUE THREAD

**Issue by Patbox** [TheEpicBlock/PPeTP#1]
Seems to be happening for any wolf/cat that is (was?) loaded or is close to spawn. None of reported entities had an owner.
Mod was added into Polymania modpack.

**Comment by Patbox** [comment]
After checking, it seems to happen to all tamable entities without owner

**Comment by TheEpicBlock** [comment]
Seems like a debug log made it through. Sorry for taking so long, was too busy with ModFest :P
