### ISSUE TITLE
NullPointerExceptions in server console

### ISSUE THREAD

**Issue by kutaxoff** [TheEpicBlock/PPeTP#2]
Added the mod (1.2.0) on my fabric 1.21.1 server, now i get a lot of errors in a console, im not sure if these errors affect the mod functionality

https://pastebin.com/LdB6VrEg

i have many mods beside this, in error traces is specifically mentioned c2me

it may be related to the fact that nearby pets are of an owner that is not currently on the server, also my server is in an offline mode

**Comment by TheEpicBlock** [comment]
This has been fixed in PPeTP 1.2.1, thank you for reporting!
